Output "/Users/kaypark/workspace/colorscheme/nvim-nepes/docs/light.gif"
Set Width 1280
Set Height 720
Set FontSize 14

Type "nvim -c 'set background=light' -c 'colorscheme nepes' /Users/kaypark/workspace/colorscheme/nepes-palette/captures/samples/showcase.py"
Enter
Sleep 3s
Screenshot "/Users/kaypark/workspace/colorscheme/nvim-nepes/docs/light.png"
Sleep 1s
Type "gg"
Sleep 0.5s
Type "G"
Sleep 0.5s
Type ":q!"
Enter
